import { SUFFIX, FETCH } from './util';

const actionTypes = {
  user: {
    FETCH_USER_INFO: 'FETCH_USER_INFO',
    FETCH_USER_INFO_START: 'FETCH_USER_INFO_START',
    FETCH_USER_INFO_SUCCESS: 'FETCH_USER_INFO_SUCCESS',
    FETCH_USER_INFO_FAIL: 'FETCH_USER_INFO_FAIL',
    LOGIN: 'LOGIN',
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
    REGISTER: 'REGISTER',
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL'
  },
  common: {
    FETCH_PAGE_LIST: 'FETCH_PAGE_LIST',
    FETCH_PAGE_LIST_START: 'FETCH_PAGE_LIST_START',
    FETCH_PAGE_LIST_SUCCESS: 'FETCH_PAGE_LIST_SUCCESS',
    FETCH_PAGE_LIST_FAIL: 'FETCH_PAGE_LIST_FAIL',
    FETCH_PROBLEM_LIST: 'FETCH_PROBLEM_LIST',
    FETCH_PROBLEM_LIST_START: 'FETCH_PROBLEM_LIST_START',
    FETCH_PROBLEM_LIST_SUCCESS: 'FETCH_PROBLEM_LIST_SUCCESS',
    FETCH_PROBLEM_LIST_FAIL: 'FETCH_PROBLEM_LIST_FAIL',
    FETCH_STATUS_LIST: 'FETCH_STATUS_LIST',
    FETCH_STATUS_LIST_START: 'FETCH_STATUS_LIST_START',
    FETCH_STATUS_LIST_SUCCESS: 'FETCH_STATUS_LIST_SUCCESS',
    FETCH_STATUS_LIST_FAIL: 'FETCH_STATUS_LIST_FAIL',
    FETCH_PROBLEM_DETAIL: 'FETCH_PROBLEM_DETAIL',
    FETCH_PROBLEM_DETAIL_START: 'FETCH_PROBLEM_DETAIL_START',
    FETCH_PROBLEM_DETAIL_SUCCESS: 'FETCH_PROBLEM_DETAIL_SUCCESS',
    FETCH_PROBLEM_DETAIL_FAIL: 'FETCH_PROBLEM_DETAIL_FAIL',
    APP_INIT: 'APP_INIT'
  },
  suffix: SUFFIX,
  prefix: {
    FETCH
  }
};

export { actionTypes };
